// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../mobile/error.dart';
import '../mobile/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<VaultStatus> initializeRuntime({required String dataRoot}) =>
    RustLib.instance.api.crateApiMobileInitializeRuntime(dataRoot: dataRoot);

Future<VaultStatus> vaultStatus() =>
    RustLib.instance.api.crateApiMobileVaultStatus();

Future<VaultStatus> createVault({required String password}) =>
    RustLib.instance.api.crateApiMobileCreateVault(password: password);

Future<VaultStatus> unlockVault({required String password}) =>
    RustLib.instance.api.crateApiMobileUnlockVault(password: password);

Future<VaultStatus> lockVault() =>
    RustLib.instance.api.crateApiMobileLockVault();

Future<EntryPage> listEntries({
  required int page,
  required int pageSize,
  required String search,
  String? tag,
  String? group,
  bool? starred,
  required bool deleted,
}) => RustLib.instance.api.crateApiMobileListEntries(
  page: page,
  pageSize: pageSize,
  search: search,
  tag: tag,
  group: group,
  starred: starred,
  deleted: deleted,
);

Future<EntryRecord> getEntry({required String id}) =>
    RustLib.instance.api.crateApiMobileGetEntry(id: id);

Future<OperationResult> saveEntry({
  String? id,
  required EntryDraft draft,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileSaveEntry(
  id: id,
  draft: draft,
  expectedRevision: expectedRevision,
);

Future<OperationResult> trashEntry({
  required String id,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileTrashEntry(
  id: id,
  expectedRevision: expectedRevision,
);

Future<OperationResult> restoreEntry({
  required String id,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileRestoreEntry(
  id: id,
  expectedRevision: expectedRevision,
);

Future<OperationResult> purgeEntry({
  required String id,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobilePurgeEntry(
  id: id,
  expectedRevision: expectedRevision,
);

Future<List<TaxonomyRecord>> listTaxonomy({required String kind}) =>
    RustLib.instance.api.crateApiMobileListTaxonomy(kind: kind);

Future<OperationResult> saveTaxonomy({
  required String kind,
  String? oldName,
  required String name,
  required String description,
  String? color,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileSaveTaxonomy(
  kind: kind,
  oldName: oldName,
  name: name,
  description: description,
  color: color,
  expectedRevision: expectedRevision,
);

Future<OperationResult> deleteTaxonomy({
  required String kind,
  required String name,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileDeleteTaxonomy(
  kind: kind,
  name: name,
  expectedRevision: expectedRevision,
);

Future<OperationResult> deleteTaxonomies({
  required String kind,
  required List<String> names,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileDeleteTaxonomies(
  kind: kind,
  names: names,
  expectedRevision: expectedRevision,
);

Future<OperationResult> saveGroupOrder({
  required List<String> names,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileSaveGroupOrder(
  names: names,
  expectedRevision: expectedRevision,
);

Future<Uint8List> exportEncryptedVault() =>
    RustLib.instance.api.crateApiMobileExportEncryptedVault();

Future<ImportPreview> previewImport({
  required List<int> content,
  required String password,
}) => RustLib.instance.api.crateApiMobilePreviewImport(
  content: content,
  password: password,
);

Future<OperationResult> applyImport({required String token}) =>
    RustLib.instance.api.crateApiMobileApplyImport(token: token);

Future<ImportPreview?> pendingImportPreview() =>
    RustLib.instance.api.crateApiMobilePendingImportPreview();

Future<List<RecoverySnapshot>> listRecoverySnapshots() =>
    RustLib.instance.api.crateApiMobileListRecoverySnapshots();

Future<ImportPreview> previewRecovery({
  required String id,
  required String password,
}) => RustLib.instance.api.crateApiMobilePreviewRecovery(
  id: id,
  password: password,
);

Future<OperationResult> changePassword({
  required String newPassword,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileChangePassword(
  newPassword: newPassword,
  expectedRevision: expectedRevision,
);

Future<AiStatus> aiStatus() => RustLib.instance.api.crateApiMobileAiStatus();

Future<AiHttpRequest> prepareAiModelsRequest({
  required String baseUrl,
  required String apiKey,
}) => RustLib.instance.api.crateApiMobilePrepareAiModelsRequest(
  baseUrl: baseUrl,
  apiKey: apiKey,
);

Future<List<String>> parseAiModelsResponse({required String content}) =>
    RustLib.instance.api.crateApiMobileParseAiModelsResponse(content: content);

Future<AiHttpRequest> prepareAiVerifyRequest({
  required String baseUrl,
  required String apiKey,
  required String model,
}) => RustLib.instance.api.crateApiMobilePrepareAiVerifyRequest(
  baseUrl: baseUrl,
  apiKey: apiKey,
  model: model,
);

Future<void> verifyAiResponse({required String content}) =>
    RustLib.instance.api.crateApiMobileVerifyAiResponse(content: content);

Future<AiStatus> saveAiSettings({
  required String baseUrl,
  required String apiKey,
  required String model,
}) => RustLib.instance.api.crateApiMobileSaveAiSettings(
  baseUrl: baseUrl,
  apiKey: apiKey,
  model: model,
);

Future<AiStatus> clearAiSettings() =>
    RustLib.instance.api.crateApiMobileClearAiSettings();

Future<AiRequestPlan> prepareAiRequest({
  required String kind,
  required String input,
  String? entryId,
  required String userPrompt,
}) => RustLib.instance.api.crateApiMobilePrepareAiRequest(
  kind: kind,
  input: input,
  entryId: entryId,
  userPrompt: userPrompt,
);

Future<AiPreview> consumeAiResponse({
  required String token,
  required String content,
}) => RustLib.instance.api.crateApiMobileConsumeAiResponse(
  token: token,
  content: content,
);

Future<AiPreview?> pendingAiPreview() =>
    RustLib.instance.api.crateApiMobilePendingAiPreview();

Future<OperationResult> applyAiPreview({
  required String token,
  required List<String> selectedItemIds,
  required BigInt expectedRevision,
}) => RustLib.instance.api.crateApiMobileApplyAiPreview(
  token: token,
  selectedItemIds: selectedItemIds,
  expectedRevision: expectedRevision,
);
