// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AiHttpHeader {
  final String name;
  final String value;

  const AiHttpHeader({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiHttpHeader &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class AiHttpRequest {
  final String method;
  final String url;
  final List<AiHttpHeader> headers;
  final String body;
  final int timeoutSeconds;

  const AiHttpRequest({
    required this.method,
    required this.url,
    required this.headers,
    required this.body,
    required this.timeoutSeconds,
  });

  @override
  int get hashCode =>
      method.hashCode ^
      url.hashCode ^
      headers.hashCode ^
      body.hashCode ^
      timeoutSeconds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiHttpRequest &&
          runtimeType == other.runtimeType &&
          method == other.method &&
          url == other.url &&
          headers == other.headers &&
          body == other.body &&
          timeoutSeconds == other.timeoutSeconds;
}

class AiPreview {
  final String token;
  final String kind;
  final String title;
  final BigInt sourceRevision;
  final List<AiPreviewItem> items;
  final List<String> warnings;
  final String privacyNote;

  const AiPreview({
    required this.token,
    required this.kind,
    required this.title,
    required this.sourceRevision,
    required this.items,
    required this.warnings,
    required this.privacyNote,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      sourceRevision.hashCode ^
      items.hashCode ^
      warnings.hashCode ^
      privacyNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiPreview &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          kind == other.kind &&
          title == other.title &&
          sourceRevision == other.sourceRevision &&
          items == other.items &&
          warnings == other.warnings &&
          privacyNote == other.privacyNote;
}

class AiPreviewDetail {
  final String label;
  final String value;
  final bool sensitive;
  final String changeType;

  const AiPreviewDetail({
    required this.label,
    required this.value,
    required this.sensitive,
    required this.changeType,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      value.hashCode ^
      sensitive.hashCode ^
      changeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiPreviewDetail &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          value == other.value &&
          sensitive == other.sensitive &&
          changeType == other.changeType;
}

class AiPreviewItem {
  final String id;
  final String title;
  final String subtitle;
  final List<AiPreviewDetail> details;

  const AiPreviewItem({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.details,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ subtitle.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiPreviewItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          subtitle == other.subtitle &&
          details == other.details;
}

class AiRequestPlan {
  final String token;
  final AiHttpRequest request;
  final AiSendSummary summary;

  const AiRequestPlan({
    required this.token,
    required this.request,
    required this.summary,
  });

  @override
  int get hashCode => token.hashCode ^ request.hashCode ^ summary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiRequestPlan &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          request == other.request &&
          summary == other.summary;
}

class AiSendSummary {
  final String title;
  final int entryCount;
  final int inputChars;
  final bool includesFieldValues;
  final List<String> categories;
  final String privacyNote;

  const AiSendSummary({
    required this.title,
    required this.entryCount,
    required this.inputChars,
    required this.includesFieldValues,
    required this.categories,
    required this.privacyNote,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      entryCount.hashCode ^
      inputChars.hashCode ^
      includesFieldValues.hashCode ^
      categories.hashCode ^
      privacyNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiSendSummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          entryCount == other.entryCount &&
          inputChars == other.inputChars &&
          includesFieldValues == other.includesFieldValues &&
          categories == other.categories &&
          privacyNote == other.privacyNote;
}

class AiStatus {
  final bool configured;
  final String baseUrl;
  final String model;
  final String apiKeyMask;

  const AiStatus({
    required this.configured,
    required this.baseUrl,
    required this.model,
    required this.apiKeyMask,
  });

  @override
  int get hashCode =>
      configured.hashCode ^
      baseUrl.hashCode ^
      model.hashCode ^
      apiKeyMask.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiStatus &&
          runtimeType == other.runtimeType &&
          configured == other.configured &&
          baseUrl == other.baseUrl &&
          model == other.model &&
          apiKeyMask == other.apiKeyMask;
}

class EntryDraft {
  final String title;
  final String url;
  final bool starred;
  final List<String> tags;
  final List<String> groups;
  final List<FieldRecord> fields;
  final String remarks;

  const EntryDraft({
    required this.title,
    required this.url,
    required this.starred,
    required this.tags,
    required this.groups,
    required this.fields,
    required this.remarks,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      url.hashCode ^
      starred.hashCode ^
      tags.hashCode ^
      groups.hashCode ^
      fields.hashCode ^
      remarks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryDraft &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          url == other.url &&
          starred == other.starred &&
          tags == other.tags &&
          groups == other.groups &&
          fields == other.fields &&
          remarks == other.remarks;
}

class EntryPage {
  final List<EntryRecord> items;
  final int page;
  final int pageSize;
  final int total;
  final int totalPages;
  final BigInt revision;

  const EntryPage({
    required this.items,
    required this.page,
    required this.pageSize,
    required this.total,
    required this.totalPages,
    required this.revision,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      page.hashCode ^
      pageSize.hashCode ^
      total.hashCode ^
      totalPages.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          pageSize == other.pageSize &&
          total == other.total &&
          totalPages == other.totalPages &&
          revision == other.revision;
}

class EntryRecord {
  final String id;
  final String title;
  final String url;
  final bool starred;
  final List<String> tags;
  final List<String> groups;
  final List<FieldRecord> fields;
  final String remarks;
  final String createdAt;
  final String updatedAt;
  final bool deleted;
  final String? deletedAt;

  const EntryRecord({
    required this.id,
    required this.title,
    required this.url,
    required this.starred,
    required this.tags,
    required this.groups,
    required this.fields,
    required this.remarks,
    required this.createdAt,
    required this.updatedAt,
    required this.deleted,
    this.deletedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      url.hashCode ^
      starred.hashCode ^
      tags.hashCode ^
      groups.hashCode ^
      fields.hashCode ^
      remarks.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      deleted.hashCode ^
      deletedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EntryRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          url == other.url &&
          starred == other.starred &&
          tags == other.tags &&
          groups == other.groups &&
          fields == other.fields &&
          remarks == other.remarks &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          deleted == other.deleted &&
          deletedAt == other.deletedAt;
}

class FieldRecord {
  final String name;
  final String value;
  final bool copyable;
  final bool hidden;

  const FieldRecord({
    required this.name,
    required this.value,
    required this.copyable,
    required this.hidden,
  });

  @override
  int get hashCode =>
      name.hashCode ^ value.hashCode ^ copyable.hashCode ^ hidden.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value &&
          copyable == other.copyable &&
          hidden == other.hidden;
}

class ImportPreview {
  final String token;
  final int entries;
  final int deletedEntries;
  final int tags;
  final int groups;
  final BigInt sourceRevision;

  const ImportPreview({
    required this.token,
    required this.entries,
    required this.deletedEntries,
    required this.tags,
    required this.groups,
    required this.sourceRevision,
  });

  @override
  int get hashCode =>
      token.hashCode ^
      entries.hashCode ^
      deletedEntries.hashCode ^
      tags.hashCode ^
      groups.hashCode ^
      sourceRevision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportPreview &&
          runtimeType == other.runtimeType &&
          token == other.token &&
          entries == other.entries &&
          deletedEntries == other.deletedEntries &&
          tags == other.tags &&
          groups == other.groups &&
          sourceRevision == other.sourceRevision;
}

class OperationResult {
  final BigInt revision;
  final String message;

  const OperationResult({required this.revision, required this.message});

  @override
  int get hashCode => revision.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OperationResult &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          message == other.message;
}

class RecoverySnapshot {
  final String id;
  final String createdAt;
  final BigInt sizeBytes;

  const RecoverySnapshot({
    required this.id,
    required this.createdAt,
    required this.sizeBytes,
  });

  @override
  int get hashCode => id.hashCode ^ createdAt.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecoverySnapshot &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          createdAt == other.createdAt &&
          sizeBytes == other.sizeBytes;
}

class TaxonomyRecord {
  final String name;
  final String description;
  final String color;
  final int count;
  final PlatformInt64? orderIndex;

  const TaxonomyRecord({
    required this.name,
    required this.description,
    required this.color,
    required this.count,
    this.orderIndex,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      description.hashCode ^
      color.hashCode ^
      count.hashCode ^
      orderIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaxonomyRecord &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          color == other.color &&
          count == other.count &&
          orderIndex == other.orderIndex;
}

class VaultStatus {
  final bool initialized;
  final bool unlocked;
  final BigInt revision;
  final int entryCount;
  final int deletedCount;

  const VaultStatus({
    required this.initialized,
    required this.unlocked,
    required this.revision,
    required this.entryCount,
    required this.deletedCount,
  });

  @override
  int get hashCode =>
      initialized.hashCode ^
      unlocked.hashCode ^
      revision.hashCode ^
      entryCount.hashCode ^
      deletedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          initialized == other.initialized &&
          unlocked == other.unlocked &&
          revision == other.revision &&
          entryCount == other.entryCount &&
          deletedCount == other.deletedCount;
}
