// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/mobile.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'mobile/error.dart';
import 'mobile/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiHttpHeader dco_decode_ai_http_header(dynamic raw);

  @protected
  AiHttpRequest dco_decode_ai_http_request(dynamic raw);

  @protected
  AiPreview dco_decode_ai_preview(dynamic raw);

  @protected
  AiPreviewDetail dco_decode_ai_preview_detail(dynamic raw);

  @protected
  AiPreviewItem dco_decode_ai_preview_item(dynamic raw);

  @protected
  AiRequestPlan dco_decode_ai_request_plan(dynamic raw);

  @protected
  AiSendSummary dco_decode_ai_send_summary(dynamic raw);

  @protected
  AiStatus dco_decode_ai_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiPreview dco_decode_box_autoadd_ai_preview(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  EntryDraft dco_decode_box_autoadd_entry_draft(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ImportPreview dco_decode_box_autoadd_import_preview(dynamic raw);

  @protected
  EntryDraft dco_decode_entry_draft(dynamic raw);

  @protected
  EntryPage dco_decode_entry_page(dynamic raw);

  @protected
  EntryRecord dco_decode_entry_record(dynamic raw);

  @protected
  FieldRecord dco_decode_field_record(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportPreview dco_decode_import_preview(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiHttpHeader> dco_decode_list_ai_http_header(dynamic raw);

  @protected
  List<AiPreviewDetail> dco_decode_list_ai_preview_detail(dynamic raw);

  @protected
  List<AiPreviewItem> dco_decode_list_ai_preview_item(dynamic raw);

  @protected
  List<EntryRecord> dco_decode_list_entry_record(dynamic raw);

  @protected
  List<FieldRecord> dco_decode_list_field_record(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecoverySnapshot> dco_decode_list_recovery_snapshot(dynamic raw);

  @protected
  List<TaxonomyRecord> dco_decode_list_taxonomy_record(dynamic raw);

  @protected
  MobileError dco_decode_mobile_error(dynamic raw);

  @protected
  OperationResult dco_decode_operation_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AiPreview? dco_decode_opt_box_autoadd_ai_preview(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ImportPreview? dco_decode_opt_box_autoadd_import_preview(dynamic raw);

  @protected
  RecoverySnapshot dco_decode_recovery_snapshot(dynamic raw);

  @protected
  TaxonomyRecord dco_decode_taxonomy_record(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VaultStatus dco_decode_vault_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiHttpHeader sse_decode_ai_http_header(SseDeserializer deserializer);

  @protected
  AiHttpRequest sse_decode_ai_http_request(SseDeserializer deserializer);

  @protected
  AiPreview sse_decode_ai_preview(SseDeserializer deserializer);

  @protected
  AiPreviewDetail sse_decode_ai_preview_detail(SseDeserializer deserializer);

  @protected
  AiPreviewItem sse_decode_ai_preview_item(SseDeserializer deserializer);

  @protected
  AiRequestPlan sse_decode_ai_request_plan(SseDeserializer deserializer);

  @protected
  AiSendSummary sse_decode_ai_send_summary(SseDeserializer deserializer);

  @protected
  AiStatus sse_decode_ai_status(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiPreview sse_decode_box_autoadd_ai_preview(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  EntryDraft sse_decode_box_autoadd_entry_draft(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview sse_decode_box_autoadd_import_preview(
    SseDeserializer deserializer,
  );

  @protected
  EntryDraft sse_decode_entry_draft(SseDeserializer deserializer);

  @protected
  EntryPage sse_decode_entry_page(SseDeserializer deserializer);

  @protected
  EntryRecord sse_decode_entry_record(SseDeserializer deserializer);

  @protected
  FieldRecord sse_decode_field_record(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview sse_decode_import_preview(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiHttpHeader> sse_decode_list_ai_http_header(
    SseDeserializer deserializer,
  );

  @protected
  List<AiPreviewDetail> sse_decode_list_ai_preview_detail(
    SseDeserializer deserializer,
  );

  @protected
  List<AiPreviewItem> sse_decode_list_ai_preview_item(
    SseDeserializer deserializer,
  );

  @protected
  List<EntryRecord> sse_decode_list_entry_record(SseDeserializer deserializer);

  @protected
  List<FieldRecord> sse_decode_list_field_record(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecoverySnapshot> sse_decode_list_recovery_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  List<TaxonomyRecord> sse_decode_list_taxonomy_record(
    SseDeserializer deserializer,
  );

  @protected
  MobileError sse_decode_mobile_error(SseDeserializer deserializer);

  @protected
  OperationResult sse_decode_operation_result(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AiPreview? sse_decode_opt_box_autoadd_ai_preview(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ImportPreview? sse_decode_opt_box_autoadd_import_preview(
    SseDeserializer deserializer,
  );

  @protected
  RecoverySnapshot sse_decode_recovery_snapshot(SseDeserializer deserializer);

  @protected
  TaxonomyRecord sse_decode_taxonomy_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VaultStatus sse_decode_vault_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_http_header(AiHttpHeader self, SseSerializer serializer);

  @protected
  void sse_encode_ai_http_request(AiHttpRequest self, SseSerializer serializer);

  @protected
  void sse_encode_ai_preview(AiPreview self, SseSerializer serializer);

  @protected
  void sse_encode_ai_preview_detail(
    AiPreviewDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_preview_item(AiPreviewItem self, SseSerializer serializer);

  @protected
  void sse_encode_ai_request_plan(AiRequestPlan self, SseSerializer serializer);

  @protected
  void sse_encode_ai_send_summary(AiSendSummary self, SseSerializer serializer);

  @protected
  void sse_encode_ai_status(AiStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_preview(
    AiPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entry_draft(
    EntryDraft self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_preview(
    ImportPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_draft(EntryDraft self, SseSerializer serializer);

  @protected
  void sse_encode_entry_page(EntryPage self, SseSerializer serializer);

  @protected
  void sse_encode_entry_record(EntryRecord self, SseSerializer serializer);

  @protected
  void sse_encode_field_record(FieldRecord self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_preview(ImportPreview self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_http_header(
    List<AiHttpHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_preview_detail(
    List<AiPreviewDetail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_preview_item(
    List<AiPreviewItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_record(
    List<EntryRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_record(
    List<FieldRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recovery_snapshot(
    List<RecoverySnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_taxonomy_record(
    List<TaxonomyRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_error(MobileError self, SseSerializer serializer);

  @protected
  void sse_encode_operation_result(
    OperationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ai_preview(
    AiPreview? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_import_preview(
    ImportPreview? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_recovery_snapshot(
    RecoverySnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_taxonomy_record(
    TaxonomyRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vault_status(VaultStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
